baseURL = "https://adrochoa.github.io"
title = "Math, Music, Misc."
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishdir = "public"

[params]
  description = "an esoteric corner of the web"
  copyright = "©2022 {{% fontawesome "github-alt" %}} {{% fontawesome "twitter" %}}"
  dark = "on"
  highlight = true

#[Params.social.share]
#  facebook = true
#  linkedin = true
#  twitter = true
#  whatsapp = true
#  email = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
